services:
  backend:
    image: caiobatista/votacao
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_container:5432/postgres
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbserver
    depends_on:
      - db_container

  db_container:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbserver

volumes:
  db_data:

networks:
  votacao_network:
    driver: bridge